name: Update NEWS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'NEWS.md'
      - 'DESCRIPTION'

jobs:
  update-news:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: Update NEWS.md')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::autonewsmd, any::here

      - name: Update NEWS.md
        run: |
          library(autonewsmd)
          an <- autonewsmd$new(repo_name = "ComptoxR", repo_path = getwd())
          an$generate()
          an$write(force = TRUE)
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add NEWS.md
          if git diff --cached --quiet; then
            echo "No changes to NEWS.md"
          else
            git commit -m "chore: Update NEWS.md [skip ci]"
            git push
          fi
